<!-- 
========================================================================
LICENSE AGREEMENT:
This software is distributed WITHOUT ANY WARRANTY and without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
========================================================================
This copy of Checker (an automated compare tool) is licensed under the
Lesser General Public License (LGPL), version 3 ("the License").

See the License for details about distribution rights, 
modification and transformation of it.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.
========================================================================
Copyright:
(c) 2010-2015 by InterSecurity GmbH & Co. KG, Germany
========================================================================
@Author: Eduard Huber
@Version: 1.0
======================================================================== 
--><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:cs="http://checker.bintellix.de/checkset/" xmlns:local="http://compare.bintellix.de/local/" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xhtml="http://www.w3.org/1999/xhtml" exclude-result-prefixes="local xhtml" version="3.0"><xsl:output version="1.1" method="xml" encoding="UTF-8" indent="no" omit-xml-declaration="yes"/>
    <!-- <xsl:namespace-alias stylesheet-prefix="xhtml" result-prefix="" exclude-result-prefixes="xhtml"/> --><xsl:strip-space elements="*"/><xsl:param name="path" required="yes"/><xsl:param name="filename" required="yes"/><xsl:param name="group" select="''"/><xsl:param name="step" select="''"/><xsl:param name="ruleset" select="''"/><xsl:param name="runset" select="''"/><xsl:param name="lang" select="'en'"/><xsl:param name="ct-home-db" required="yes"/><xsl:param name="ct-home-web" required="yes"/><xsl:function name="local:replaceVariables"><xsl:param name="Replacement" required="yes"/><xsl:value-of select="replace(replace(replace(replace(replace($Replacement,'\$lang', $lang),'\$group', $group),'\$step', $step),'\$ruleset', $ruleset),'\$runset', $runset)"/></xsl:function><xsl:variable name="url" select="concat($path, $filename)"/><xsl:variable name="sitemap" select="document(concat($ct-home-db,'/sitemap.xml'))"/><xsl:variable name="title"><xsl:variable name="t" select="local:replaceVariables($sitemap//page[replace(@url,'\?.*','')=$url]/title)"/><xsl:choose><xsl:when test="$t != ''"><xsl:value-of select="$t"/></xsl:when><xsl:otherwise><xsl:text>UNKNOWN</xsl:text></xsl:otherwise></xsl:choose></xsl:variable><xsl:template match="/"><html xmlns="http://www.w3.org/1999/xhtml"><head><title><xsl:value-of select="$title"/></title><xsl:if test="not(//*:meta[@http-equiv])"><meta http-equiv="X-UA-Compatible" content="IE=8"/> <!-- IE=edge --></xsl:if><meta charset="UTF-8"/><link rel="stylesheet" type="text/css" href="{$ct-home-web}/base/checker.css"/><xsl:apply-templates select="html/head/* | xhtml:html/xhtml:head/*"/></head><body><div id="menu" class="breadcrump"><div style="float:left;">
                        <!-- [Debug: <xsl:value-of select="$url"/>] --><span>You are here: </span><xsl:for-each select="$sitemap//page[descendant-or-self::*/replace(@url,'\?.*','')=$url]"><xsl:if test="position() != 1"><xsl:text>&#160;&gt;&#160;</xsl:text></xsl:if><a href="{replace(concat($ct-home-web, local:replaceVariables(@url)),'//','/')}"><xsl:value-of select="local:replaceVariables(title)"/></a></xsl:for-each><xsl:text>&#160;&#160;</xsl:text></div><xsl:for-each select="//menu/crosslinks/crosslink"><xsl:text>&#160;&#160;</xsl:text><xsl:variable name="url" select="replace(concat($ct-home-web,local:replaceVariables($path),@url),'//','/')"/><xsl:choose><xsl:when test="contains($url,'?')"><a href="{substring-before($url,'?')}?{substring-after($url,'?')}" class="buttonComp"><xsl:if test="@external='yes'"><xsl:attribute name="target" select="'_blank'"/></xsl:if><xsl:value-of select="@title"/><xsl:if test="@external='yes'"><image src="{$ct-home-web}/base/images/action_extlink.png" title="open in new window" height="10px" width="10px"/></xsl:if></a></xsl:when><xsl:otherwise><a href="{$url}" class="buttonComp"><xsl:if test="@external='yes'"><xsl:attribute name="target" select="'_blank'"/></xsl:if><xsl:value-of select="@title"/><xsl:if test="@external='yes'"><image src="{$ct-home-web}/base/images/action_extlink.png" title="open in new window" height="10px" width="10px"/></xsl:if></a></xsl:otherwise></xsl:choose></xsl:for-each></div><div><h2><xsl:value-of select="$title"/></h2><div id="content"><xsl:apply-templates/></div></div></body></html></xsl:template><xsl:template match="error | xhtml:error | cs:error"><xhtml:div class="Error"><xsl:apply-templates/></xhtml:div></xsl:template><xsl:template match="xhtml:html | html"><xsl:apply-templates/></xsl:template><xsl:template match="xhtml:html/xhtml:head | html/head">
        <!-- no longer needed as part of root now --></xsl:template><xsl:template match="xhtml:html/xhtml:body | html/body"><xsl:apply-templates/></xsl:template><xsl:template match="xhtml:title | title">
        <!-- nothing to do --></xsl:template><xsl:template match="xhtml:subtitle"><xhtml:h3><xsl:apply-templates/></xhtml:h3></xsl:template>
    <!-- <xsl:template match="xhtml:menu | menue" priority="1"/> --><xsl:template match="xhtml:error | error" priority="1"><xhtml:div class="error"><xhtml:h3>An error occured:</xhtml:h3><xsl:apply-templates/></xhtml:div></xsl:template><xsl:template match="*[namespace-uri()='http://www.w3.org/1999/xhtml']" priority="-1"><xsl:element name="{local-name()}" namespace="http://www.w3.org/1999/xhtml"><xsl:apply-templates select="node() | @*"/></xsl:element></xsl:template><xsl:template match="*[namespace-uri()='http://www.w3.org/2002/xforms']" priority="-1"><xsl:element name="{concat('xf:', local-name())}" namespace="http://www.w3.org/2002/xforms"><xsl:apply-templates select="node() | @*"/></xsl:element></xsl:template><xsl:template match="node()|@*" priority="-2"><xsl:copy copy-namespaces="yes"><xsl:apply-templates select="node()|@*"/></xsl:copy></xsl:template></xsl:stylesheet>